apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: tp3
spec:
  spec:
  containers:
  - name: nginx
    image: somafairey/tp3.5:nginx
    ports: 
     - containerPort: 80 
  - name: go
    image: somafairey/tp3.5:hellogo
    ports:
     - containerPort: 8080 
  imagePullSecrets:
  - name: tp3secretkey-gmtc572dt8 
