apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webpod
  name: webpod
  namespace: web
spec:
  containers:
  - command:
    - nginx
    - -g daemon off;
    - -q
    image: nginx
    name: webpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
